import { Pic } from "./app/shared/model/pic";

export const sample_pics:Pic[] =[
  {
id:'1',
name:'tiger',
tag:['wild','non veg'],
caption:'voilent if hungry but lazy in nature',
imageUrl:'assets/pic-1.jpg',
origins:['tropical regions','asia'],
  },
{id:'2',
name:'Lion',
tag:['wild','non veg'],
caption:'voilent if hungry but lazy in nature',
imageUrl:'assets/pic-2.jpg',
origins:['tropical regions','asia'],
  },
{
id:'3',
name:'jaguar',
tag:['wild','non veg'],
caption:'a silent hunter ',
imageUrl:'assets/pic-3.jpg',
origins:['tropical regions','asia'],
  },
{
id:'4',
name:'wolf',
tag:['wild','non veg'],
caption:'hunt in a group never been in captative',
imageUrl:'assets/pic-4.jpg',
origins:['tropical regions','asia'],
  },
{
id:'5',
name:'elephant',
tag:['wild','vegetarian'],
caption:'freindly in nature sometimes violent',
imageUrl:'assets/pic-5.jpg',
origins:['tropical regions','asia'],
  },
{
id:'6',
name:'deer',
tag:['wild','vegetarian'],
caption:'afraid of being killed by salmon bhoy',
imageUrl:'assets/pic-6.jpg',
origins:['tropical regions','asia'],
  },
{
id:'7',
name:'monkey',
tag:['wild','vegetarian'],
caption:"gandiji's favourite animal",
imageUrl:'assets/pic-7.jpg',
origins:['tropical regions','asia'],
  },
{
id:'8',
name:'zebra',
tag:['wild','vegetarian'],
caption:'identity confusion between donkey and horse',
imageUrl:'assets/pic-8.jpg',
origins:['grass land ', 'savana woodlands'],
  },
]
